spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: 192.168.47.1:8848

dubbo:
  scan:
    base-packages: com.learn.dubbo.service.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://192.168.47.1:8848
  cloud:
    subscribed-services: dubbo-provider

server:
  port: 9081
