spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      server-addr: 192.168.47.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8888
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true
