spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      server-addr: 192.168.47.128:8848
server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
