spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      server-addr: 192.168.47.1:8848
    sentinel:
      transport:
        dashboard: localhost:8888
feign:
  sentinel:
    enabled: true

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"

